# N: 200
N: 100 # ajustado a parámetros de Verlet
# R: 120
R: 10 # ajustado a parámetros de Verlet
epsilon: 10.0
# sigma: 5.0
sigma: 1 # ajustado a parámetros de Verlet
kB_T: 0.01
step_size: 1.0  # 10% de sigma
max_steps: 30000
fps: 240